name: Deploy

on:
  push:
    branches:
      - main

env:
  PNPM_VERSION: 6.26.1
  DEPLOY_TARGET: 'GitHub Pages'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 12.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist
          git-config-name: simplabs
          git-config-email: info@simplabs.com
          single-commit: true

