name: Release

on:
  push:
    tags:
      - 'v*'

env:
  PNPM_VERSION: 8.6.10

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.4.0
      - uses: pnpm/action-setup@v2.3.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 12.x
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
