name: Release

on:
  push:
    tags:
      - 'v*'

env:
  PNPM_VERSION: 6.32.23

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: 12.x
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
